variable aws-environment {}
variable project-name {}
variable sg-eks-master {}
variable app_subnet_ids {}
variable sg-eks-worker {}
variable key-pair-name {}
variable instance-type {}
variable vpc_id {}
variable aws_lb_target_group {}
variable sg-eks-alb {}